Minor type fix
Original version resulted in
=> Rails 2.3.18 application starting on http://0.0.0.0:2500
/home/s/instiki-svn/script/server:81:in `<top (required)>': undefined method `=~' for #<Pathname:/home/s/instiki-svn/config.ru> (NoMethodError)
	from ./instiki:6:in `load'
	from ./instiki:6:in `<main>'